### ISSUE TITLE
 Unable to genarate table in dynamoDB using lamda function

### ISSUE THREAD

**Issue by jovelcjose** [aws/aws-greengrass-core-sdk-python#1]
I am trying the below code
 aws-greengrass-core-sdk-python/examples/TrafficLight/carAggregator.py

While delopying the Greengrass group i have no errors, similarly i have no errors while running both the devices.

I am from eu-central, i tried changing location from default N.virgina to frankfurt, At both locations a table 'carStats' is not created. As recommended i waited for 3 mins as the code pushes values after light turns green 3 times.

Only change i made: GG trafficlight for me is another raspberry Pi, which are connected to physical leds. Therefore subscriptions are made accordingly with the update/documents topic of my rasperrypi thing.

what should be the reason for lamda not generating a table? my lamda and greengrass group has full access dynamodb polices attached to its roles as well.

**Comment by MikeDombo** [comment]
Hi jovelcjose, 
Did you include the boto3 library in the zip which you uploaded to lambda?

Closing since this is so old, but feel free to reopen.
