### ISSUE TITLE
Stream Manager - how to read only latest message?

### ISSUE THREAD

**Issue by ramgrandhi** [aws/aws-greengrass-core-sdk-python#12]
Hello -
I'm looking to use stream manager to read only the latest message (at any given moment).

Whenever i invoke read_mesages(..), it always returns from the start of the stream.

Is it possible with the ReadMessagesOptions that I can configure to retrieve only the latest message at any given time?

Thanks in advance!

Cheers.

**Comment by MikeDombo** [comment]
The ReadMessagesOptions includes a `desired_start_sequence_number` option which you can set to the last sequence number in the stream. Get the last sequence number by calling `describe_message_stream` and then take `newest_sequence_number` from that result.

**Comment by ramgrandhi** [comment]
That's awesome @MikeDombo for your super-fast response! 

I'm giving it a try now......
