### ISSUE TITLE
Compatibility with Python 3.6

### ISSUE THREAD

**Issue by bdatdo0601** [aws/aws-greengrass-core-sdk-python#2]
Hello,

Currently AWS Greengrass SDK only support lambda with Python2.7 or NodeJS 6, which are either deprecated or soon to be deprecated.

We need updates to run later version of each language (i.e: Python 3.6 and Node 10).

**Comment by mariopoeta** [comment]
I have the same "issue"

**Comment by mariopoeta** [comment]
@bdatdo0601 https://aws.amazon.com/about-aws/whats-new/2019/04/aws-iot-greengrass-adds-support-python-3-7-node-v-8-10-0-and-expands-support-elliptic-curve-cryptography/

**Comment by bdatdo0601** [comment]
Yeap i just upgrade the my fleets 😅. Closing the issue now
