### ISSUE TITLE
Greengrass common missing

### ISSUE THREAD

**Issue by Ycallaer** [aws/aws-greengrass-core-sdk-python#3]
Hi,
When installing the greengrass SDK there seems to be an issue when you make a unit test.
When executing a unit test that imports a python file (which imports greengrasssdk) the following error occurs:

```
/python3.6/site-packages/greengrasssdk/Lambda.py:10: in <module>
    from greengrass_common.function_arn_fields import FunctionArnFields
E   ModuleNotFoundError: No module named 'greengrass_common'
```
When you pip install greengrasssdk this package is not part of the installation. I can not find any way to install this package. 
Any ideas ?

Thanks.

**Comment by Ycallaer** [comment]
Ok the workaround is going to the machine were greengrass is installed and there you can find the greengrass_common package, but ideally this should be a dependency on the greengrass sdk

**Comment by broAhmed** [comment]
Just noticed this in the docs:

> The Test button on the AWS Lambda console doesn't work with this function. The AWS IoT Greengrass Core SDK doesn't contain modules that are required to run your Greengrass Lambda functions independently in the AWS Lambda console. These modules (for example, greengrass_common) are supplied to the functions after they are deployed to your Greengrass core.

Source: https://docs.aws.amazon.com/greengrass/latest/developerguide/create-lambda.html

**Comment by panjinbo** [comment]
Greengrass Common is packaged with Greengrass Software. We can only test the lambda function in the greengrass runtime. If we just normally run the lambda code it will have dependencies error

**Comment by Ycallaer** [comment]
Testing software when you deploy it to the runtime seems to go against the normal way of writing software (writing unit /integration tests).
So what is the general approach to test a lambda for greengrass ? I don't like to deploy multiple times and adding tons of logging just to see if my code breaks somewhere.

**Comment by panjinbo** [comment]
If you only test the logic of the lambda, you can test it in aws lambda console with payload. If you want to test the communication between GGC and lambda, you can only deploy the lambda and test it locally.

**Comment by mrpackethead** [comment]
My lambdas need to interface with sensors and communicate with various hardware devices.     I can't test the 'logic' remotely in the labmda console, as it doesnt make sense. 

But deploying it every time i want to edit and test is super annoying as well.

**Comment by FRVisser** [comment]
@mrpackethead You can edit the python file locally `/greengrass/ggc/deployment/lambda/arn.aws.lambda************/pythonfile.py` and manually restart greengrass.

**Comment by FRVisser** [comment]
And I succesfully imported the `greengrass_common` libraries by adding symbolic links to my lambda folder

`ln -s /data/greengrass/ggc/packages/1.9.1/runtime/python/* . `

**Comment by Moumita-Bhattacharjee** [comment]
{
  "errorMessage": "Unable to import module 'lambda_function': No module named 'greengrass_common'",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "c0da4c21-4e65-4adc-adb7-914833fda2e7",
  "stackTrace": []
}

I have faced this problem after use python greengrass sdk in my lambda fucntion . How to solve it ? kindly guide me.

**Comment by MikeDombo** [comment]
The common library is not available to you. You cannot use the Greengrass SDK unless the lambda is executing in Greengrass. You cannot run it in AWS lambda or on your local machine. It only works when Greengrass runs it.

In Greengrass V2, lambda is not recommended. We suggest you use a native Greengrass V2 component https://docs.aws.amazon.com/greengrass/v2/developerguide/develop-greengrass-components.html

**Comment by Moumita-Bhattacharjee** [comment]
Thank you so much

**Comment by RahulDey12** [comment]
> The common library is not available to you. You cannot use the Greengrass SDK unless the lambda is executing in Greengrass. You cannot run it in AWS lambda or on your local machine. It only works when Greengrass runs it.
> 
> In Greengrass V2, lambda is not recommended. We suggest you use a native Greengrass V2 component https://docs.aws.amazon.com/greengrass/v2/developerguide/develop-greengrass-components.html

Can you please suggest a way to interact with the MQTT on production? 

Cause there is no way to publish message to MQTT outside of the AWS Console

**Comment by MikeDombo** [comment]
Interact with MQTT how? I am not sure what you're looking for.

There is an example right here in this repository for how to publish using this SDK. https://github.com/aws/aws-greengrass-core-sdk-python/blob/b172a6ae3d1536dbd2db216f92170036800f5436/examples/HelloWorld/greengrassHelloWorld.py#L43

In Greengrass V2 I do not recommend lambda. Use a native component and use IPC to publish. https://docs.aws.amazon.com/greengrass/v2/developerguide/ipc-iot-core-mqtt.html

**Comment by RahulDey12** [comment]
@MikeDombo No I mean if we want to publish messages other than the AWS console then how can I do it ? like I have an application that will publish message to MQTT and my IOT device will subscribe that

**Comment by MikeDombo** [comment]
MQTT Publish without using the AWS Console, I just told you how to do that using code in this repository.
