### ISSUE TITLE
Can you please add the example for DynamoDB Streams

### ISSUE THREAD

**Issue by aadu999** [aws/aws-greengrass-core-sdk-python#4]
Can you please include dynamodb stream Manager Client python example file.

**Comment by MikeDombo** [comment]
Sorry, but DynamoDB streams and Stream Manager are completely separate. Stream manager supports sending data to Kinesis and IoT Analytics currently. Learn more about Stream manager at https://docs.aws.amazon.com/greengrass/latest/developerguide/stream-manager.html
