### ISSUE TITLE
HelloWorldCounter example does not output correct message

### ISSUE THREAD

**Issue by dblunt** [aws/aws-greengrass-core-sdk-python#5]
The current version of greengrassHelloWorldCounter.py has a formatting issue on lines 53/54. When executed as a long lived lambda it should output both my_platform and my_counter. Each invocation results in my_counter increasing by one. However, the result is not as expected:

{"message": "Hello world! Sent from Greengrass Core running on platform: {}.  Invocation Count: Linux-4.19.75-v7l+-armv7l-with-debian-10.1"}

It should be:

{"message": "Hello world! Sent from Greengrass Core running on platform: Linux-4.19.75-v7l+-armv7l-with-debian-10.1.  Invocation Count: 1"}

The code in github also differs from the documentation here: https://docs.aws.amazon.com/greengrass/latest/developerguide/long-testing.html

**Comment by liuszeng** [comment]
Hi @dblunt ,

Thank you very much for pointing this out. Formatting has been fixed in a [recent commit](2c293a5058ac838572692697db4e5e41b81efe30). We will continue our internal process with the documentation updates.

Thanks,
Liusu
