### ISSUE TITLE
Lack of documentation for lambda client.

### ISSUE THREAD

**Issue by JeremyRitchie** [aws/aws-greengrass-core-sdk-python#8]
Within the greengrass developer guide there is a number of examples using GG SDK 'iot-client'.
I want to use the 'lambda' client but I have only found a single reference to it online. 

That reference (found https://github.com/aws/aws-greengrass-core-sdk-python/README.rst) does not describe any of the arguments, or explain the single example in any meaningful way. 

The code comments also do not explain the arguments or provide any more insite. 

EDIT:

After running into further questions about using the lambda client, i did find the boto3 documentation for lambda (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.invoke). There i was able to find the information i needed around the arguments of the invoke method. I found this reference in the comments of the _invoke_internal method. 

I still maintain this information should be more easily accessible and examples using both the iot-client and lambda client should be apparent in the developer guide. 

EDIT 2:

For example, the Boto3 lambda invoke method documentation state that the "Qualifyer" can be a version number or alias; however i have found the alias does not work at all when it comes to greengrass. These differences should be documented for developers.

**Comment by jbutler** [comment]
Hi Jeremy,

I'm sorry you had issues finding this information and appreciate you taking the time to provide feedback. I've opened a ticket with our doc writers and we'll work to see how we can close these gaps.

In the meantime, if you encounter any other issues using Greengrass, please get in touch with us over in the AWS forums.
https://forums.aws.amazon.com/forum.jspa?forumID=254

Thanks,
-joe
